- hosts: localhost
  connection: local
  remote_user: "{{ user }}"
  gather_facts: yes
  vars_files:
    - user.conf.yaml
  vars:
    jdks:
      - { version: 11 }
      - { version: 17 }
  tasks:
    - name: Install command line tools using Homebrew
      homebrew:
        name: "{{ item.name }}"
        state: present
      ignore_errors: yes
      with_flattened:
        - { name: openjdk@11 }
        - { name: openjdk@17 }
        - { name: maven }
        - { name: helm }
        - { name: jq }
        - { name: yq }
        - { name: python }
        - { name: terraform }
        - { name: zsh }
        - { name: git }
   
    - name: Install cask packages using Homebrew
      when: ansible_distribution == 'MacOSX'
      register: result
      ignore_errors: yes
      homebrew_cask:
        name: "{{ item.name }}"
        state: installed
      ignore_errors: yes
      with_flattened:
        - { name: iterm2 }
        - { name: webstorm }
        - { name: intellij-idea }
        - { name: sublime-text }
        - { name: docker }
        - { name: visual-studio-code }
        - { name: postman }
        - { name: azure-data-studio }

    - name: Generate SSH for GitHub
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 2048
        comment: " {{ email }} "
    
    - name: Copy ssh content into Git
      debug:
        msg: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    - name: Pause for git ssh copy paste
      pause:
        prompt: "Press enter when finished copying ssh key value"
    
    - name: Update git conf
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      with_flattened:
        - { name: user.name , value: "{{ user }}" }
        - { name: user.email , value: "{{ email }}" }
        - { name: color.ui , value: "auto" }
        - { name: push.default , value: "simple" }
    
    - name: Install oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      ignore_errors: yes
    
    - name: Clone powerlevel10k theme into zsh custom theme dir
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ '/Users/' + user + '/.oh-my-zsh/custom/themes/powerlevel10k' }}"
        single_branch: yes
        version: master

    - name: Update ZSH_THEME in zshrc file
      ansible.builtin.lineinfile: 
        path: ~/.zshrc
        regexp: '^ZSH_THEME='
        line: ZSH_THEME="powerlevel10k/powerlevel10k"
      
    - name: Download custom color profile
      shell:
        cmd: sh -c "$(curl -fsSl https://raw.githubusercontent.com/josean-dev/dev-environment-files/main/coolnight.itermcolors --output ~/Downloads/coolnight.itermcolors)"
      ignore_errors: yes

    - name: Set JAVA_HOME var
      ansible.builtin.set_fact:
        ansible_env:
          java_home_path: "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"

    - name: Add JAVA_HOME to .zshrc
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        block: |
          export JAVA_HOME="{{ ansible_env.java_home_path }}"
        insertafter: EOF
        create: yes
